### ISSUE TITLE
StorageException: Message: {"Errors":["Request rate is large"]}

### ISSUE THREAD

**Issue by takekazuomi** [Azure-Samples/azure-cosmos-db-table-dotnet-getting-started#1]
I got the following error on the Premium Table.
I think that StorageException  is not able to handle 429 error of DocumentDB style (json).
The original Storage Client processes XML error messages.

## Reproduction
Execute command on Azure DC

In an environment where throttling is not applied, problems are not placed.

```
Creating Table if it doesn't exist...
Running inserts:
        Insert #74 completed in 5.9768 ms..
Unhandled Exception: Microsoft.WindowsAzure.Storage.StorageException: Message: {"Errors":["Request rate is large"]}
ActivityId: 1be5a451-eb01-42bc-b3de-b65aec85c3c9, Request URI: /apps/10e450c3-81a1-4f4f-82b6-6c64e2fc5408/services/0c48e7fc-a2f7-41ba-8beb-02a16212280f/partitions/ec316c45-82cf-49e7-852a-ff7a220884bf/replicas/131389566084516313p/ ---> Microsoft.Azure.Documents.RequestRateTooLargeException: Message: {"Errors":["Request rate is large"]}
ActivityId: 1be5a451-eb01-42bc-b3de-b65aec85c3c9, Request URI: /apps/10e450c3-81a1-4f4f-82b6-6c64e2fc5408/services/0c48e7fc-a2f7-41ba-8beb-02a16212280f/partitions/ec316c45-82cf-49e7-852a-ff7a220884bf/replicas/131389566084516313p/
   at Microsoft.Azure.Documents.TransportClient.ThrowIfFailed(String resourceAddress, StoreResponse storeResponse, Uri physicalAddress, Guid activityId)
   at Microsoft.Azure.Documents.RntbdTransportClient.<InvokeStoreAsync>d__0.MoveNext()

... snip ....

at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.WindowsAzure.Storage.Table.Extensions.TableExtensionOperationHelper.<HandleInsertAsync>d__1d.MoveNext() in f:\_Bld\14958\10329\Sources\Product\SDK\Table\.net\Lib\WindowsDesktop\Table\Extensions\TableExtensionOperationHelper.cs:line 331
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.WindowsAzure.Storage.Table.Extensions.TableExtensionOperationHelper.<ExecuteOperationAsync>d__0`1.MoveNext() in f:\_Bld\14958\10329\Sources\Product\SDK\Table\.net\Lib\WindowsDesktop\Table\Extensions\TableExtensionOperationHelper.cs:line 53
   --- End of inner exception stack trace ---
   at Microsoft.WindowsAzure.Storage.Table.Extensions.TableExtensionOperationHelper.<ExecuteOperationAsync>d__0`1.MoveNext() in f:\_Bld\14958\10329\Sources\Product\SDK\Table\.net\Lib\WindowsDesktop\Table\Extensions\TableExtensionOperationHelper.cs:line 89
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.WindowsAzure.Storage.Table.Extensions.TableExtensionRetryPolicy.<ExecuteUnderRetryPolicy>d__0`1.MoveNext() in f:\_Bld\14958\10329\Sources\Product\SDK\Table\.net\Lib\WindowsDesktop\Table\Extensions\TableExtensionRetryPolicy.cs:line 96
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.WindowsAzure.Storage.Table.Extensions.TableExtensionExecutor.Execute[TResult,TOperation](TOperation operation, CloudTableClient client, CloudTable table, TableRequestOptions requestOptions, OperationContext operationContext) in f:\_Bld\14958\10329\Sources\Product\SDK\Table\.net\Lib\WindowsDesktop\Table\Extensions\TableExtensionExecutor.cs:line 39
   at Microsoft.WindowsAzure.Storage.Table.TableOperation.Execute(CloudTableClient client, CloudTable table, TableRequestOptions requestOptions, OperationContext operationContext) in f:\_Bld\14958\10329\Sources\Product\SDK\Table\.net\Lib\ClassLibraryCommon\Table\TableOperation.cs:line 41
   at Microsoft.WindowsAzure.Storage.Table.CloudTable.Execute(TableOperation operation, TableRequestOptions requestOptions, OperationContext operationContext) in f:\_Bld\14958\10329\Sources\Product\SDK\Table\.net\Lib\ClassLibraryCommon\Table\CloudTable.cs:line 52
   at TableSBS.Program.Run(CloudTableClient tableClient, Int32 numIterations) in C:\GitHub\azure-cosmos-db-table-dotnet-getting-started\PremiumTableGetStarted\Program.cs:line 100
   at TableSBS.Program.Main(String[] args) in C:\GitHub\azure-cosmos-db-table-dotnet-getting-started\PremiumTableGetStarted\Program.cs:line 55
   
```

**Comment by takekazuomi** [comment]
The problem seems to be different. I will close it.
